"""
Network Visibility Map API — serves the pre-built graph data (network_graph_data.json)
generated by build_graph.py from the SAP CSV files.

This endpoint does NOT require a database connection; it reads the static JSON
directly from the data directory.
"""

from fastapi import APIRouter, HTTPException
from fastapi.responses import JSONResponse
import os
import json

router = APIRouter()

# Path to the pre-built graph data JSON
DATA_DIR = r"c:\Users\abcom\OneDrive - Ofi Benelux B.V\Desktop\my-postgres-project\data"
GRAPH_JSON = os.path.join(DATA_DIR, "network_graph_data.json")


@router.get("/graph-data")
async def get_graph_data():
    """
    Returns the full network graph data (nodes + edges) for the
    FrieslandCampina supply chain network visibility map.
    No auth required for internal dashboard use.
    """
    if not os.path.exists(GRAPH_JSON):
        raise HTTPException(
            status_code=404,
            detail=f"network_graph_data.json not found. Run build_graph.py first."
        )

    try:
        with open(GRAPH_JSON, "r", encoding="utf-8") as f:
            data = json.load(f)
        return JSONResponse(content=data)
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/graph-stats")
async def get_graph_stats():
    """
    Returns high-level statistics about the network graph.
    """
    if not os.path.exists(GRAPH_JSON):
        raise HTTPException(
            status_code=404,
            detail="network_graph_data.json not found."
        )

    try:
        with open(GRAPH_JSON, "r", encoding="utf-8") as f:
            data = json.load(f)

        nodes = data.get("nodes", [])
        edges = data.get("edges", [])

        # Node counts by type
        node_types = {}
        for n in nodes:
            t = n.get("type", "unknown")
            node_types[t] = node_types.get(t, 0) + 1

        # Edge counts by type
        edge_types = {}
        total_qty = 0
        for e in edges:
            t = e.get("type", "unknown")
            edge_types[t] = edge_types.get(t, 0) + 1
            total_qty += e.get("qty_kg", 0)

        # Total milk kg
        milk_kg = sum(
            e.get("qty_kg", 0) for e in edges if e.get("type") == "milk_intake"
        )
        sto_kg = sum(
            e.get("qty_kg", 0) for e in edges if e.get("type") == "sto_transfer"
        )
        delivery_kg = sum(
            e.get("qty_kg", 0) for e in edges if e.get("type") == "sales_delivery"
        )

        return {
            "total_nodes": len(nodes),
            "total_edges": len(edges),
            "node_types": node_types,
            "edge_types": edge_types,
            "total_qty_kg": round(total_qty, 0),
            "milk_intake_kg": round(milk_kg, 0),
            "sto_transfer_kg": round(sto_kg, 0),
            "delivery_kg": round(delivery_kg, 0),
        }
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))
